jobs:
  include:
    - language: node_js
      node_js: 16
      python: "3.9.2"
      addons:
        sonarcloud:
          organization: "swsnu"
          token:
            secure: "d2o4WCYebaPPjVE9yVhZ3kzSwj4vysjbe0I3LxO6U4K0Uf4ItpoYwCcczlJ0ILELcZGP8jwj46eI44M73S4xDyQ5jTs2+1waapLxXDzyaHUqg4iYCaWkDK8hJD/P7McizyZvy4pE0kCl92wERaqRiPQT/seKy9zxGu/baE7BD+bufo/s7td23rb3nAO3vxTE462gq4qpd29G1RsKeMltOP/Gam0NxrnOvb+X8pBEDjwU5usny2frWO96qvN0TZrZXPVbbBsvV/ZhCmL66vWb7wnKJK/GkLgxlPqIsJITF84XR0Qe7/uReVHEaLxH8zCPcMOZwP+pYnBIkdCjhHu65yzsPE5fTGcXgdgOyapKnbLLl+PWe/Q6yxQXsP32sxGw4r7anKpHvYSnbir7lL+fHWpaiLnXVDA6pX31B0RoU38GK+CReWgdSnJ1BH+RAZCC49LBJefYNnQGXo61v2iRRSlcWp/+C8b9GEeDy1TuoZK1dXaHiezq7ve5esw/8LxjUjwmk2T0OzHe/j3lr8HITZMjilU6FpxFFKJ8ZAeAbTd7e90kPETXIJynRfm4DKWIb4GDLA80ilEuFZdg6+3fPkINSbsmNUQ4SAxYVGOH5Q6o4WtDcTrJyFB/tF4c93BnMSPez1EO43edbDFYPaYzIITLVhhMPtt5/WF3WzcJ9X8="
      install:
        - source ~/virtualenv/python3.7/bin/activate
        - gem install coveralls-lcov
        - cd frontend
        - yarn install
        - yarn global add coveralls
        - cd ../backend/rejourn
        - pip install -r requirements.txt
        - python -m pip install Pillow 
        - pip install coveralls
      script:
        - cd ../../frontend
        - ./node_modules/.bin/eslint src/
        - yarn test --coverage --watchAll=false
        - coveralls-lcov -v -n coverage/lcov.info > coverage.json
        - cd ../backend/rejourn
        - python3 manage.py makemigrations project
        - python3 manage.py migrate
        - pylint project --load-plugins pylint_django
        - coverage run --source='.' manage.py test
        - coverage xml
        - coveralls --merge=../../frontend/coverage.json
        - cd ..
        - cd ..
        - sonar-scanner
      env:
        global:
          secure: VYGboiwY/KSgOYySKJ2ZHEaWE1k3tz+wEt5l27soR77MSHC3hPigKPiE0wt4rJoEruefJZvz8NqwxBYa0hdFWfQh1jxtpYVcq8PWhm4hcpsq6xaLUn7Mt1FopvZbnydrgOQ7yftC8poESaBRHfv0bK6a7vuMqISgbD17gUPN5TfAI8/5rSzGxB0pcKAHKhhy5dXxuuUtyKWHyrd9okeoW8k+BmZCoemH5ICfdU7Z3fu9SwwXn1rbZXGBVpRqzeolhAiCpOT5l5/LajW2hq62i2qnTU5rBG8d1MLvo4KzHBcl/eKylDjGt+8sAYQGTL9DBLoSw08uBhl7qABLP14b8S2K/p1c5+2KbH2/bjZmOeLGnoNoA5yjsPswjE8jIUb/FlaQj2fzr5B18l3I19jr5UKrJsyScgt76wxS/zo1pT+ZDGmVDdCGIykpenZ7ykGg1RBr9CX4r9rJWgQkSPyFZpdAl/mlG6yUB4tOaqYfBJmAKxLHkRTS4W3sjhcKYLHNCS0TltuMlHtogcFl17cQKhG2oQDNNYmSmh1+XwGlgROIKlPWvC43VI2Nr6KyHvfsS8CjvSNTvVjbVGWAxbEUTStZ0DjbUMjTh1/tkfJbJmECO2ixubqCEJ/PBIthJ7HLmV/UoeLMHzBqQhr/hcRrThZtpk+iEA5/5jfNiwzs2wk=