version: "3.9"

services:
    db:
        image: postgres
        volumes:
            - ./backend/rejourn/data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    backend:
        build:
            context: ./backend/rejourn
        command: bash -c "gunicorn rejourn.wsgi --bind 0.0.0.0:8000 --env DJANGO_SETTINGS_MODULE='rejourn.settings_prod' --capture-output --workers 3 --log-level debug"
        ports:
            - "8000:8000"
        volumes:
            - ./backend/rejourn:/django
        environment:
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        depends_on:
            - db
    frontend:
        build:
            context: ./frontend
        volumes:
            - react_build:/react/build
    nginx:
        image: nginx:latest
        ports:
            - 80:8080
            - 443:8443
        volumes:
            - ./nginx/nginx-ssl.conf:/etc/nginx/conf.d/default.conf:rw
            - react_build:/var/www/react
            - ./nginx/certs:/certs
            - ./backend/rejourn/media:/django/media
        depends_on:
            - backend
            - frontend
volumes:
    react_build:
