# Generated by Django 3.2.8 on 2021-10-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('repo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('repo_name', models.CharField(max_length=120)),
                ('setting_visibility', models.IntegerField(choices=[(1, 'Public'), (2, 'Private'), (3, 'Friends Only')])),
                ('setting_fork_permission', models.IntegerField(choices=[(1, 'Public'), (2, 'Private'), (3, 'Friends Only')])),
            ],
        ),
    ]
