# Generated by Django 3.2.8 on 2021-10-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_repository'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='setting_fork_permission',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='setting_visibility',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='repository',
            name='setting',
            field=models.IntegerField(choices=[(0, 'Public'), (1, 'Friends Only'), (2, 'Private')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='setting',
            field=models.IntegerField(choices=[(0, 'Public'), (1, 'Friends Only'), (2, 'Private')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(max_length=120, primary_key=True, serialize=False),
        ),
    ]
