# Generated by Django 3.2.8 on 2021-10-28 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20211028_0403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='setting',
            new_name='repo_setting',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='description',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='setting',
            new_name='user_setting',
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_project_user_friends_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='realname',
            field=models.TextField(default='', max_length=129),
        ),
    ]
